// <auto-generated />
using System;
using DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260629151512_PaymentModuleOverhaul")]
    partial class PaymentModuleOverhaul
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.EF.Models.CardioSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("EquipmentUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("CardioSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 25,
                            ClassName = "HIIT Training",
                            DayOfWeek = "Monday, Wednesday, Friday",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            EquipmentUsed = "Treadmill, Battle Ropes, Kettlebells",
                            Instructor = "Mike Johnson",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            ClassName = "Cycling Class",
                            DayOfWeek = "Tuesday, Thursday",
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            EquipmentUsed = "Stationary Bikes",
                            Instructor = "Mike Johnson",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            ClassName = "Aerobics",
                            DayOfWeek = "Monday, Wednesday, Saturday",
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            EquipmentUsed = "Open Floor, Step Platforms",
                            Instructor = "John Carter",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Free Weights",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Professional 20kg Olympic barbell with weight plates (5kg to 25kg). Essential for compound lifts.",
                            IsActive = true,
                            Name = "Olympic Barbell Set"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cardio",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Commercial-grade treadmill with 22km/h max speed, incline 0-15%, heart rate monitor, and touchscreen display.",
                            IsActive = true,
                            Name = "Treadmill Pro 5000"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Strength Machines",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Full commercial cable crossover machine with adjustable pulleys for cable flyes, rows, and tricep pushdowns.",
                            IsActive = true,
                            Name = "Cable Cross Machine"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Free Weights",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete rubber hex dumbbell set with dedicated storage rack. Perfect for isolation exercises.",
                            IsActive = true,
                            Name = "Dumbbells Set (5-50kg)"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cardio",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indoor cycling bike with magnetic resistance, adjustable seat, and performance tracking display.",
                            IsActive = true,
                            Name = "Stationary Bike"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Strength Machines",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Counter-balanced Smith machine for guided barbell training. Ideal for squats, bench press, and shoulder press.",
                            IsActive = true,
                            Name = "Smith Machine"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.EquipmentInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId")
                        .IsUnique();

                    b.ToTable("EquipmentInventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentId = 1,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 25000m,
                            Quantity = 10,
                            StockStatus = "Available",
                            Supplier = "SportsPro BD"
                        },
                        new
                        {
                            Id = 2,
                            EquipmentId = 2,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 150000m,
                            Quantity = 8,
                            StockStatus = "Available",
                            Supplier = "FitTech International"
                        },
                        new
                        {
                            Id = 3,
                            EquipmentId = 3,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 120000m,
                            Quantity = 3,
                            StockStatus = "Available",
                            Supplier = "FitTech International"
                        },
                        new
                        {
                            Id = 4,
                            EquipmentId = 4,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 80000m,
                            Quantity = 2,
                            StockStatus = "Low",
                            Supplier = "SportsPro BD"
                        },
                        new
                        {
                            Id = 5,
                            EquipmentId = 5,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 45000m,
                            Quantity = 12,
                            StockStatus = "Available",
                            Supplier = "FitTech International"
                        },
                        new
                        {
                            Id = 6,
                            EquipmentId = 6,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 200000m,
                            Quantity = 4,
                            StockStatus = "Available",
                            Supplier = "GymWorld"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.GymSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerImage3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTagline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("YouTubeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GymSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutUs = "PowerFit Gym is a state-of-the-art fitness center dedicated to helping you achieve your health and fitness goals. With world-class equipment, expert trainers, and a motivating environment, we've been transforming lives since 2020.",
                            Address = "123 Fitness Street, Gulshan-1, Dhaka 1212, Bangladesh",
                            Email = "info@powerfitgym.com",
                            GymName = "PowerFit Gym",
                            HeroTagline = "Transform Your Body. Transform Your Life.",
                            Phone = "+880 1712-345678",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.GymShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("GymShifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            Description = "Early morning workout session",
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            IsActive = true,
                            ShiftName = "Morning Shift",
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Description = "Midday workout session",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsActive = true,
                            ShiftName = "Afternoon Shift",
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 60,
                            Description = "After-work evening session - most popular",
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            IsActive = true,
                            ShiftName = "Evening Shift",
                            StartTime = new TimeSpan(0, 17, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GymId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Dhaka",
                            BloodGroup = "O+",
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "Jane Brown",
                            EmergencyPhone = "01798765432",
                            Gender = "Male",
                            GymId = "",
                            JoinDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01712345678",
                            UserId = "user-member-001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Park Ave, Dhaka",
                            BloodGroup = "A+",
                            DateOfBirth = new DateTime(1998, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "Tom Wilson",
                            EmergencyPhone = "01823456789",
                            Gender = "Female",
                            GymId = "",
                            JoinDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01856789012",
                            UserId = "user-member-002"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.MembershipPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MembershipPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Benefits = "Full gym access;Locker room;Free WiFi;1 fitness assessment",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Perfect for trying out our gym. Includes full access to all equipment and basic amenities.",
                            DurationDays = 30,
                            IsActive = true,
                            Name = "Monthly Package",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 2,
                            Benefits = "Full gym access;Locker room;Free WiFi;2 fitness assessments;Diet consultation",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Our most popular package. Save 22% compared to monthly billing.",
                            DurationDays = 90,
                            IsActive = true,
                            Name = "3-Month Package",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 3,
                            Benefits = "Full gym access;Locker room;Free WiFi;Quarterly assessments;Diet consultation;1 month PT trial",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Serious results require serious commitment. Great value with added benefits.",
                            DurationDays = 180,
                            IsActive = true,
                            Name = "6-Month Package",
                            Price = 6000m
                        },
                        new
                        {
                            Id = 4,
                            Benefits = "Full gym access;Locker room;Free WiFi;Monthly assessments;Diet consultation;3 months PT included;Priority booking;Guest passes x5",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The ultimate membership. Best value with all premium benefits included.",
                            DurationDays = 365,
                            IsActive = true,
                            Name = "Annual Package",
                            Price = 10000m
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.MembershipPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardioScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrainerAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("YogaScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardioScheduleId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("YogaScheduleId");

                    b.ToTable("MembershipPurchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MemberId = 1,
                            PackageId = 2,
                            PaymentStatus = "Paid",
                            PurchaseDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftId = 1,
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MemberId = 2,
                            PackageId = 1,
                            PaymentStatus = "Paid",
                            PurchaseDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftId = 2,
                            StartDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YogaScheduleId = 1
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DAL.EF.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("MembershipPurchaseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DAL.EF.Models.PersonalTrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChargePerSession")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("PersonalTrainingSessions");
                });

            modelBuilder.Entity("DAL.EF.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableTimeSlots")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("GymId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxStudentsPerSlot")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PersonalTrainingCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TrainingCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrainingTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Expert in powerlifting and muscle building with 8 years of coaching experience.",
                            Certifications = "NSCA-CSCS, ACE-CPT",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 8,
                            GymId = "",
                            IsAvailable = true,
                            JoinDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudentsPerSlot = 2,
                            MonthlySalary = 45000m,
                            PersonalTrainingCharge = 0m,
                            Phone = "",
                            Specialization = "Strength & Conditioning",
                            TrainingCharge = 3000m,
                            UserId = "user-trainer-001"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Certified yoga instructor specializing in Hatha and Vinyasa yoga.",
                            Certifications = "RYT-500, ACE-GFI",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 6,
                            GymId = "",
                            IsAvailable = true,
                            JoinDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudentsPerSlot = 2,
                            MonthlySalary = 38000m,
                            PersonalTrainingCharge = 0m,
                            Phone = "",
                            Specialization = "Yoga & Flexibility",
                            TrainingCharge = 2500m,
                            UserId = "user-trainer-002"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Specialist in HIIT training and nutrition coaching for weight management.",
                            Certifications = "ACSM-CPT, Precision Nutrition L1",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 5,
                            GymId = "",
                            IsAvailable = true,
                            JoinDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxStudentsPerSlot = 2,
                            MonthlySalary = 35000m,
                            PersonalTrainingCharge = 0m,
                            Phone = "",
                            Specialization = "Cardio & Weight Loss",
                            TrainingCharge = 2000m,
                            UserId = "user-trainer-003"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<string>("TrainingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkoutPlan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MemberId = 1,
                            TrainerId = 1,
                            TrainingNotes = "Focus on compound movements",
                            WorkoutPlan = "5-day split: Chest/Back/Legs/Shoulders/Arms"
                        },
                        new
                        {
                            Id = 2,
                            AssignedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MemberId = 2,
                            TrainerId = 2,
                            TrainingNotes = "Beginner friendly routine",
                            WorkoutPlan = "3-day full body workout + yoga"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerPayments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 45000m,
                            CreatedAt = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastPaidDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = 3,
                            PaymentMethod = "Cash",
                            PaymentStatus = "Paid",
                            TotalSalary = 45000m,
                            TrainerId = 1,
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 38000m,
                            CreatedAt = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastPaidDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = 3,
                            PaymentMethod = "Cash",
                            PaymentStatus = "Paid",
                            TotalSalary = 38000m,
                            TrainerId = 2,
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            AmountPaid = 0m,
                            CreatedAt = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = 3,
                            PaymentMethod = "Cash",
                            PaymentStatus = "Unpaid",
                            TotalSalary = 35000m,
                            TrainerId = 3,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent trainer! Very motivating and knowledgeable.",
                            IsApproved = true,
                            MemberId = 1,
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Great yoga sessions, very patient instructor.",
                            IsApproved = true,
                            MemberId = 2,
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-admin-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "13d1921a-dd55-4d59-890b-a5c14dc3ccc1",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDz5Pi8Ot7XNJS74oloiQhpOEiwfNbgpLMneLGVGylput0N7twH/lju6Q7mWWyKgPg==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "a6fe1100-076d-420d-89ac-dc1aefde9c16",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "user-trainer-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "75921df5-93ab-40ad-9f83-a14c8736a80d",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.trainer@gym.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Carter",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.TRAINER@GYM.COM",
                            NormalizedUserName = "JOHN.TRAINER@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF57H5BKt3OtOzXPS4ctlJ9z8roHxU+TaKQOQIycGU142R8DzAJ+qW3zWdqKvFo/Cw==",
                            PhoneNumberConfirmed = false,
                            Role = "Trainer",
                            SecurityStamp = "b9e07f0e-688a-43a0-8cca-61beea2d3f98",
                            TwoFactorEnabled = false,
                            UserName = "john.trainer@gym.com"
                        },
                        new
                        {
                            Id = "user-trainer-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea6a81c9-131b-4d64-8b4a-0c75c373ee9e",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.trainer@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Sara",
                            IsActive = true,
                            LastName = "Miles",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA.TRAINER@GYM.COM",
                            NormalizedUserName = "SARA.TRAINER@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIndLXYhxr5eGqFWSaLbXck7eqK+ETgijohxe8RuEAuJOcFChS60cAV0d/miKxiD7w==",
                            PhoneNumberConfirmed = false,
                            Role = "Trainer",
                            SecurityStamp = "baec1432-22e5-46e7-951f-67246aac12a9",
                            TwoFactorEnabled = false,
                            UserName = "sara.trainer@gym.com"
                        },
                        new
                        {
                            Id = "user-trainer-003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8230eca7-8c68-452e-b667-ac6f78b64180",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mike.trainer@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Mike",
                            IsActive = true,
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "MIKE.TRAINER@GYM.COM",
                            NormalizedUserName = "MIKE.TRAINER@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEu52TLfoiMySVZQ/OY3R9cf7mR61xPiIKcga2VPCF1we9YLX4w03gMfR8F+O2ee7Q==",
                            PhoneNumberConfirmed = false,
                            Role = "Trainer",
                            SecurityStamp = "03ebb81d-7593-4aa3-9084-a22f99b49163",
                            TwoFactorEnabled = false,
                            UserName = "mike.trainer@gym.com"
                        },
                        new
                        {
                            Id = "user-member-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ba17968c-8e78-4826-ae2a-4c297bb9e8b1",
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.member@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Alex",
                            IsActive = true,
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALEX.MEMBER@GYM.COM",
                            NormalizedUserName = "ALEX.MEMBER@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHMwffiNVbIhaiyKTtrlJ2X6ntzRogRIwLHPAQmkdaN5lV9v4wROLyFA+ScG+TLxCQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Member",
                            SecurityStamp = "9cc79e67-8ba0-4d06-9062-53d9ddce3b04",
                            TwoFactorEnabled = false,
                            UserName = "alex.member@gym.com"
                        },
                        new
                        {
                            Id = "user-member-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2ece28d4-fdb0-4ecf-8668-466c861ad949",
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.member@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Emma",
                            IsActive = true,
                            LastName = "Wilson",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMMA.MEMBER@GYM.COM",
                            NormalizedUserName = "EMMA.MEMBER@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELoG8t1LRa3C7EN4pbY9xpl1/bZyxBOnc2V7wXzXWG3rICjpI37JJA5Goius05Vafg==",
                            PhoneNumberConfirmed = false,
                            Role = "Member",
                            SecurityStamp = "022b53b6-db0a-44b1-9fe6-9d49c33fd657",
                            TwoFactorEnabled = false,
                            UserName = "emma.member@gym.com"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.YogaSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Instructor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("YogaSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            ClassName = "Hatha Yoga",
                            DayOfWeek = "Monday, Wednesday, Friday",
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            Instructor = "Sara Miles",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            ClassName = "Vinyasa Flow",
                            DayOfWeek = "Tuesday, Thursday",
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            Instructor = "Sara Miles",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 25,
                            ClassName = "Restorative Yoga",
                            DayOfWeek = "Saturday",
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            Instructor = "Sara Miles",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "f9a94858-7319-4a6f-acb0-b81a4fdccdc7",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-trainer",
                            ConcurrencyStamp = "6034776f-d4f5-446c-ab6a-f9818c64d089",
                            Name = "Trainer",
                            NormalizedName = "TRAINER"
                        },
                        new
                        {
                            Id = "role-member",
                            ConcurrencyStamp = "732ef198-e717-418a-b396-0e5df3ba4dcc",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin-001",
                            RoleId = "role-admin"
                        },
                        new
                        {
                            UserId = "user-trainer-001",
                            RoleId = "role-trainer"
                        },
                        new
                        {
                            UserId = "user-trainer-002",
                            RoleId = "role-trainer"
                        },
                        new
                        {
                            UserId = "user-trainer-003",
                            RoleId = "role-trainer"
                        },
                        new
                        {
                            UserId = "user-member-001",
                            RoleId = "role-member"
                        },
                        new
                        {
                            UserId = "user-member-002",
                            RoleId = "role-member"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.EF.Models.EquipmentInventory", b =>
                {
                    b.HasOne("DAL.EF.Models.Equipment", "Equipment")
                        .WithOne("Inventory")
                        .HasForeignKey("DAL.EF.Models.EquipmentInventory", "EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("DAL.EF.Models.Member", b =>
                {
                    b.HasOne("DAL.EF.Models.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("DAL.EF.Models.Member", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.EF.Models.MembershipPurchase", b =>
                {
                    b.HasOne("DAL.EF.Models.CardioSchedule", "CardioSchedule")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("CardioScheduleId");

                    b.HasOne("DAL.EF.Models.Member", "Member")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.MembershipPackage", "Package")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.GymShift", "Shift")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.YogaSchedule", "YogaSchedule")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("YogaScheduleId");

                    b.Navigation("CardioSchedule");

                    b.Navigation("Member");

                    b.Navigation("Package");

                    b.Navigation("Shift");

                    b.Navigation("YogaSchedule");
                });

            modelBuilder.Entity("DAL.EF.Models.Notification", b =>
                {
                    b.HasOne("DAL.EF.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.EF.Models.Payment", b =>
                {
                    b.HasOne("DAL.EF.Models.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DAL.EF.Models.PersonalTrainingSession", b =>
                {
                    b.HasOne("DAL.EF.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.Trainer", "Trainer")
                        .WithMany("PersonalTrainingSessions")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DAL.EF.Models.Trainer", b =>
                {
                    b.HasOne("DAL.EF.Models.User", "User")
                        .WithOne("Trainer")
                        .HasForeignKey("DAL.EF.Models.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerAssignment", b =>
                {
                    b.HasOne("DAL.EF.Models.Member", "Member")
                        .WithMany("TrainerAssignments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.Trainer", "Trainer")
                        .WithMany("TrainerAssignments")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerPayment", b =>
                {
                    b.HasOne("DAL.EF.Models.Trainer", "Trainer")
                        .WithMany("TrainerPayments")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerReview", b =>
                {
                    b.HasOne("DAL.EF.Models.Member", "Member")
                        .WithMany("TrainerReviews")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.Trainer", "Trainer")
                        .WithMany("TrainerReviews")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.EF.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.EF.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.EF.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.EF.Models.CardioSchedule", b =>
                {
                    b.Navigation("MembershipPurchases");
                });

            modelBuilder.Entity("DAL.EF.Models.Equipment", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("DAL.EF.Models.GymShift", b =>
                {
                    b.Navigation("MembershipPurchases");
                });

            modelBuilder.Entity("DAL.EF.Models.Member", b =>
                {
                    b.Navigation("MembershipPurchases");

                    b.Navigation("Payments");

                    b.Navigation("TrainerAssignments");

                    b.Navigation("TrainerReviews");
                });

            modelBuilder.Entity("DAL.EF.Models.MembershipPackage", b =>
                {
                    b.Navigation("MembershipPurchases");
                });

            modelBuilder.Entity("DAL.EF.Models.Trainer", b =>
                {
                    b.Navigation("PersonalTrainingSessions");

                    b.Navigation("TrainerAssignments");

                    b.Navigation("TrainerPayments");

                    b.Navigation("TrainerReviews");
                });

            modelBuilder.Entity("DAL.EF.Models.User", b =>
                {
                    b.Navigation("Member");

                    b.Navigation("Notifications");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DAL.EF.Models.YogaSchedule", b =>
                {
                    b.Navigation("MembershipPurchases");
                });
#pragma warning restore 612, 618
        }
    }
}
