// <auto-generated />
using System;
using DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(GymDbContext))]
    partial class GymDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.EF.Models.CardioSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("EquipmentUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("CardioSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 25,
                            ClassName = "HIIT Training",
                            DayOfWeek = "Monday, Wednesday, Friday",
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            EquipmentUsed = "Treadmill, Battle Ropes, Kettlebells",
                            Instructor = "Mike Johnson",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20,
                            ClassName = "Cycling Class",
                            DayOfWeek = "Tuesday, Thursday",
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            EquipmentUsed = "Stationary Bikes",
                            Instructor = "Mike Johnson",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            ClassName = "Aerobics",
                            DayOfWeek = "Monday, Wednesday, Saturday",
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            EquipmentUsed = "Open Floor, Step Platforms",
                            Instructor = "John Carter",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Free Weights",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Professional 20kg Olympic barbell with weight plates (5kg to 25kg). Essential for compound lifts.",
                            IsActive = true,
                            Name = "Olympic Barbell Set"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cardio",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Commercial-grade treadmill with 22km/h max speed, incline 0-15%, heart rate monitor, and touchscreen display.",
                            IsActive = true,
                            Name = "Treadmill Pro 5000"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Strength Machines",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Full commercial cable crossover machine with adjustable pulleys for cable flyes, rows, and tricep pushdowns.",
                            IsActive = true,
                            Name = "Cable Cross Machine"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Free Weights",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete rubber hex dumbbell set with dedicated storage rack. Perfect for isolation exercises.",
                            IsActive = true,
                            Name = "Dumbbells Set (5-50kg)"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cardio",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indoor cycling bike with magnetic resistance, adjustable seat, and performance tracking display.",
                            IsActive = true,
                            Name = "Stationary Bike"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Strength Machines",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Counter-balanced Smith machine for guided barbell training. Ideal for squats, bench press, and shoulder press.",
                            IsActive = true,
                            Name = "Smith Machine"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.EquipmentInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId")
                        .IsUnique();

                    b.ToTable("EquipmentInventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentId = 1,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 25000m,
                            Quantity = 10,
                            StockStatus = "Available",
                            Supplier = "SportsPro BD"
                        },
                        new
                        {
                            Id = 2,
                            EquipmentId = 2,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 150000m,
                            Quantity = 8,
                            StockStatus = "Available",
                            Supplier = "FitTech International"
                        },
                        new
                        {
                            Id = 3,
                            EquipmentId = 3,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 120000m,
                            Quantity = 3,
                            StockStatus = "Available",
                            Supplier = "FitTech International"
                        },
                        new
                        {
                            Id = 4,
                            EquipmentId = 4,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 80000m,
                            Quantity = 2,
                            StockStatus = "Low",
                            Supplier = "SportsPro BD"
                        },
                        new
                        {
                            Id = 5,
                            EquipmentId = 5,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 45000m,
                            Quantity = 12,
                            StockStatus = "Available",
                            Supplier = "FitTech International"
                        },
                        new
                        {
                            Id = 6,
                            EquipmentId = 6,
                            LastUpdated = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchaseDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasePrice = 200000m,
                            Quantity = 4,
                            StockStatus = "Available",
                            Supplier = "GymWorld"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.GymSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerImage1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerImage2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerImage3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroTagline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("YouTubeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GymSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutUs = "PowerFit Gym is a state-of-the-art fitness center dedicated to helping you achieve your health and fitness goals. With world-class equipment, expert trainers, and a motivating environment, we've been transforming lives since 2020.",
                            Address = "123 Fitness Street, Gulshan-1, Dhaka 1212, Bangladesh",
                            Email = "info@powerfitgym.com",
                            GymName = "PowerFit Gym",
                            HeroTagline = "Transform Your Body. Transform Your Life.",
                            Phone = "+880 1712-345678",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.GymShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("GymShifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            Description = "Early morning workout session",
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            IsActive = true,
                            ShiftName = "Morning Shift",
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            Description = "Midday workout session",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsActive = true,
                            ShiftName = "Afternoon Shift",
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 60,
                            Description = "After-work evening session - most popular",
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            IsActive = true,
                            ShiftName = "Evening Shift",
                            StartTime = new TimeSpan(0, 17, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Dhaka",
                            BloodGroup = "O+",
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "Jane Brown",
                            EmergencyPhone = "01798765432",
                            Gender = "Male",
                            JoinDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01712345678",
                            UserId = "user-member-001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Park Ave, Dhaka",
                            BloodGroup = "A+",
                            DateOfBirth = new DateTime(1998, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContact = "Tom Wilson",
                            EmergencyPhone = "01823456789",
                            Gender = "Female",
                            JoinDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01856789012",
                            UserId = "user-member-002"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.MembershipPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MembershipPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Benefits = "Full gym access;Locker room;Free WiFi;1 fitness assessment",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Perfect for trying out our gym. Includes full access to all equipment and basic amenities.",
                            DurationDays = 30,
                            IsActive = true,
                            Name = "Monthly Package",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 2,
                            Benefits = "Full gym access;Locker room;Free WiFi;2 fitness assessments;Diet consultation",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Our most popular package. Save 22% compared to monthly billing.",
                            DurationDays = 90,
                            IsActive = true,
                            Name = "3-Month Package",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 3,
                            Benefits = "Full gym access;Locker room;Free WiFi;Quarterly assessments;Diet consultation;1 month PT trial",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Serious results require serious commitment. Great value with added benefits.",
                            DurationDays = 180,
                            IsActive = true,
                            Name = "6-Month Package",
                            Price = 6000m
                        },
                        new
                        {
                            Id = 4,
                            Benefits = "Full gym access;Locker room;Free WiFi;Monthly assessments;Diet consultation;3 months PT included;Priority booking;Guest passes x5",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The ultimate membership. Best value with all premium benefits included.",
                            DurationDays = 365,
                            IsActive = true,
                            Name = "Annual Package",
                            Price = 10000m
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.MembershipPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardioScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrainerAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("YogaScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardioScheduleId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("YogaScheduleId");

                    b.ToTable("MembershipPurchases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MemberId = 1,
                            PackageId = 2,
                            PaymentStatus = "Paid",
                            PurchaseDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftId = 1,
                            StartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MemberId = 2,
                            PackageId = 1,
                            PaymentStatus = "Paid",
                            PurchaseDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftId = 2,
                            StartDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YogaScheduleId = 1
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DAL.EF.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("MembershipPurchaseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 3500m,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            MembershipPurchaseId = 1,
                            PaymentDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1500m,
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            MembershipPurchaseId = 2,
                            PaymentDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            Status = "Paid"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlySalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Expert in powerlifting and muscle building with 8 years of coaching experience.",
                            Certifications = "NSCA-CSCS, ACE-CPT",
                            Experience = 8,
                            IsAvailable = true,
                            JoinDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlySalary = 45000m,
                            Specialization = "Strength & Conditioning",
                            UserId = "user-trainer-001"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Certified yoga instructor specializing in Hatha and Vinyasa yoga.",
                            Certifications = "RYT-500, ACE-GFI",
                            Experience = 6,
                            IsAvailable = true,
                            JoinDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlySalary = 38000m,
                            Specialization = "Yoga & Flexibility",
                            UserId = "user-trainer-002"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Specialist in HIIT training and nutrition coaching for weight management.",
                            Certifications = "ACSM-CPT, Precision Nutrition L1",
                            Experience = 5,
                            IsAvailable = true,
                            JoinDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MonthlySalary = 35000m,
                            Specialization = "Cardio & Weight Loss",
                            UserId = "user-trainer-003"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<string>("TrainingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkoutPlan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MemberId = 1,
                            TrainerId = 1,
                            TrainingNotes = "Focus on compound movements",
                            WorkoutPlan = "5-day split: Chest/Back/Legs/Shoulders/Arms"
                        },
                        new
                        {
                            Id = 2,
                            AssignedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MemberId = 2,
                            TrainerId = 2,
                            TrainingNotes = "Beginner friendly routine",
                            WorkoutPlan = "3-day full body workout + yoga"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerPayments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 45000m,
                            CreatedAt = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = 3,
                            PaidDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            TrainerId = 1,
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            Amount = 38000m,
                            CreatedAt = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = 3,
                            PaidDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            TrainerId = 2,
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Amount = 35000m,
                            CreatedAt = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = 3,
                            Status = "Pending",
                            TrainerId = 3,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent trainer! Very motivating and knowledgeable.",
                            IsApproved = true,
                            MemberId = 1,
                            Rating = 5,
                            ReviewDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Great yoga sessions, very patient instructor.",
                            IsApproved = true,
                            MemberId = 2,
                            Rating = 4,
                            ReviewDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-admin-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "62c31d0a-3106-418c-a4c8-b11a24466987",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMwHGeQth35yuqQaml1TG/8/JcqDQoHbjkmGCbHdTMenk8YbDna9CPSUF93uFV7/Eg==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "0a1acca4-7bb9-4e5c-8236-4cd1ddd094d7",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "user-trainer-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1f5ab158-310c-48ee-921a-616585f431c5",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.trainer@gym.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Carter",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.TRAINER@GYM.COM",
                            NormalizedUserName = "JOHN.TRAINER@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPPrNPUIu0OplznPUoykU66GIZ+4KcrugsqBAVdzj74xwDMQFZjQIHV9+YbEbBG1Kg==",
                            PhoneNumberConfirmed = false,
                            Role = "Trainer",
                            SecurityStamp = "a94e41d4-65ea-4efb-9f52-e31a578f0a0a",
                            TwoFactorEnabled = false,
                            UserName = "john.trainer@gym.com"
                        },
                        new
                        {
                            Id = "user-trainer-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "702dc8fe-a163-4882-81d0-30a1956f4efc",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.trainer@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Sara",
                            IsActive = true,
                            LastName = "Miles",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA.TRAINER@GYM.COM",
                            NormalizedUserName = "SARA.TRAINER@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFCdaFuM51w9DNzSGWSclQI9TyNDxDrwhTlJaD9Mu4/IWTZ2eSJCzxdIP9mhgSly8w==",
                            PhoneNumberConfirmed = false,
                            Role = "Trainer",
                            SecurityStamp = "082318a5-3310-4cf0-ab38-a4a05aa86351",
                            TwoFactorEnabled = false,
                            UserName = "sara.trainer@gym.com"
                        },
                        new
                        {
                            Id = "user-trainer-003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c5f8e950-92eb-4091-a80b-3398389f647b",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mike.trainer@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Mike",
                            IsActive = true,
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "MIKE.TRAINER@GYM.COM",
                            NormalizedUserName = "MIKE.TRAINER@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENmqwilbjGe9ovUkjnNEKoIK1tHdrhwp/hxYU0BdK5DUuLvoPcyz4jQZdq32UyqKyw==",
                            PhoneNumberConfirmed = false,
                            Role = "Trainer",
                            SecurityStamp = "0a954714-f361-448c-a0f7-daf2fb736ded",
                            TwoFactorEnabled = false,
                            UserName = "mike.trainer@gym.com"
                        },
                        new
                        {
                            Id = "user-member-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74cdc436-ca18-4fdf-9c7a-e8cf68e85c05",
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex.member@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Alex",
                            IsActive = true,
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALEX.MEMBER@GYM.COM",
                            NormalizedUserName = "ALEX.MEMBER@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELEZ2cAYB9qS4N0VP8Ffbikrgydodbo77RTbkPm8XQduLpTuQzLepXBOVvREbPL19g==",
                            PhoneNumberConfirmed = false,
                            Role = "Member",
                            SecurityStamp = "42197155-fa6e-41be-934a-923a63a73d74",
                            TwoFactorEnabled = false,
                            UserName = "alex.member@gym.com"
                        },
                        new
                        {
                            Id = "user-member-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8ee1ebc1-35b6-4a5a-9c1a-0b62f01df8f9",
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.member@gym.com",
                            EmailConfirmed = true,
                            FirstName = "Emma",
                            IsActive = true,
                            LastName = "Wilson",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMMA.MEMBER@GYM.COM",
                            NormalizedUserName = "EMMA.MEMBER@GYM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDAxxK0Rt82oI+TIb04xN0diSGqsOqbS82ksep5eqoRqvniC3TdLjq9QwdGfXfYxSA==",
                            PhoneNumberConfirmed = false,
                            Role = "Member",
                            SecurityStamp = "f94282be-9b99-4e5b-a409-71e7c1d0223e",
                            TwoFactorEnabled = false,
                            UserName = "emma.member@gym.com"
                        });
                });

            modelBuilder.Entity("DAL.EF.Models.YogaSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Instructor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("YogaSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20,
                            ClassName = "Hatha Yoga",
                            DayOfWeek = "Monday, Wednesday, Friday",
                            EndTime = new TimeSpan(0, 8, 0, 0, 0),
                            Instructor = "Sara Miles",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            ClassName = "Vinyasa Flow",
                            DayOfWeek = "Tuesday, Thursday",
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            Instructor = "Sara Miles",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 25,
                            ClassName = "Restorative Yoga",
                            DayOfWeek = "Saturday",
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            Instructor = "Sara Miles",
                            IsActive = true,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "4b9dbaf8-594d-498e-8b2f-d102d2117078",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-trainer",
                            ConcurrencyStamp = "60830331-0de8-474b-b999-eb201784ee79",
                            Name = "Trainer",
                            NormalizedName = "TRAINER"
                        },
                        new
                        {
                            Id = "role-member",
                            ConcurrencyStamp = "7cd0ea92-cd39-4798-9263-e0fbb7da9695",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin-001",
                            RoleId = "role-admin"
                        },
                        new
                        {
                            UserId = "user-trainer-001",
                            RoleId = "role-trainer"
                        },
                        new
                        {
                            UserId = "user-trainer-002",
                            RoleId = "role-trainer"
                        },
                        new
                        {
                            UserId = "user-trainer-003",
                            RoleId = "role-trainer"
                        },
                        new
                        {
                            UserId = "user-member-001",
                            RoleId = "role-member"
                        },
                        new
                        {
                            UserId = "user-member-002",
                            RoleId = "role-member"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.EF.Models.EquipmentInventory", b =>
                {
                    b.HasOne("DAL.EF.Models.Equipment", "Equipment")
                        .WithOne("Inventory")
                        .HasForeignKey("DAL.EF.Models.EquipmentInventory", "EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("DAL.EF.Models.Member", b =>
                {
                    b.HasOne("DAL.EF.Models.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("DAL.EF.Models.Member", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.EF.Models.MembershipPurchase", b =>
                {
                    b.HasOne("DAL.EF.Models.CardioSchedule", "CardioSchedule")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("CardioScheduleId");

                    b.HasOne("DAL.EF.Models.Member", "Member")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.MembershipPackage", "Package")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.GymShift", "Shift")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.YogaSchedule", "YogaSchedule")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("YogaScheduleId");

                    b.Navigation("CardioSchedule");

                    b.Navigation("Member");

                    b.Navigation("Package");

                    b.Navigation("Shift");

                    b.Navigation("YogaSchedule");
                });

            modelBuilder.Entity("DAL.EF.Models.Notification", b =>
                {
                    b.HasOne("DAL.EF.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.EF.Models.Payment", b =>
                {
                    b.HasOne("DAL.EF.Models.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DAL.EF.Models.Trainer", b =>
                {
                    b.HasOne("DAL.EF.Models.User", "User")
                        .WithOne("Trainer")
                        .HasForeignKey("DAL.EF.Models.Trainer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerAssignment", b =>
                {
                    b.HasOne("DAL.EF.Models.Member", "Member")
                        .WithMany("TrainerAssignments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.Trainer", "Trainer")
                        .WithMany("TrainerAssignments")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerPayment", b =>
                {
                    b.HasOne("DAL.EF.Models.Trainer", "Trainer")
                        .WithMany("TrainerPayments")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DAL.EF.Models.TrainerReview", b =>
                {
                    b.HasOne("DAL.EF.Models.Member", "Member")
                        .WithMany("TrainerReviews")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.Trainer", "Trainer")
                        .WithMany("TrainerReviews")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.EF.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.EF.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.EF.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.EF.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.EF.Models.CardioSchedule", b =>
                {
                    b.Navigation("MembershipPurchases");
                });

            modelBuilder.Entity("DAL.EF.Models.Equipment", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("DAL.EF.Models.GymShift", b =>
                {
                    b.Navigation("MembershipPurchases");
                });

            modelBuilder.Entity("DAL.EF.Models.Member", b =>
                {
                    b.Navigation("MembershipPurchases");

                    b.Navigation("Payments");

                    b.Navigation("TrainerAssignments");

                    b.Navigation("TrainerReviews");
                });

            modelBuilder.Entity("DAL.EF.Models.MembershipPackage", b =>
                {
                    b.Navigation("MembershipPurchases");
                });

            modelBuilder.Entity("DAL.EF.Models.Trainer", b =>
                {
                    b.Navigation("TrainerAssignments");

                    b.Navigation("TrainerPayments");

                    b.Navigation("TrainerReviews");
                });

            modelBuilder.Entity("DAL.EF.Models.User", b =>
                {
                    b.Navigation("Member");

                    b.Navigation("Notifications");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("DAL.EF.Models.YogaSchedule", b =>
                {
                    b.Navigation("MembershipPurchases");
                });
#pragma warning restore 612, 618
        }
    }
}
